### PR TITLE
CMake

### PR DESCRIPTION
**Pull request by flagarde**

### CODE REVIEW

**Comment by davea42** [comment]
I've applied your PR locally and so far all is well. Once I get to the point of
updating my local branch (so work will not be lost here) I'll close the PR.

**Comment by davea42** [comment]
A misunderstanding, if no dwarfgen, then there should be no libdwarfp either. Fixed that.

A bigger problem is that libdwarf.a is never installed, even if a static library
is called for (and if a static called for,
libdwarf.so should not be built or referenced).  
The pointless differences the IDE reformat created and the major
changes made by hand make it unclear what is wrong. Puzzling over
that now.

**Comment by davea42** [comment]
A vital element of the libdwarf build,
if (BUILD_SHARED)
    if(NOT BUILD_DWARFGEN)
      set(CMAKE_C_VISIBILITY_PRESET hidden)
    endif()
    set(COMPILER_FLAGS -DLIBDWARF_BUILD -DPIC)
else()
    set(COMPILER_FLAGS -DLIBDWARF_STATIC)
endif()
was dropped and without that...major trouble.
Other following parts in the base libdwarf/CMakeLists.txt
were removed too, and it's not clear why.

**Comment by flagarde** [comment]
> A vital element of the libdwarf build,
> if (BUILD_SHARED)
>     if(NOT BUILD_DWARFGEN)
>       set(CMAKE_C_VISIBILITY_PRESET hidden)
>     endif()
>     set(COMPILER_FLAGS -DLIBDWARF_BUILD -DPIC)
> else()
>     set(COMPILER_FLAGS -DLIBDWARF_STATIC)
> endif()
> was dropped and without that...major trouble.
> Other vital  following parts in the base libdwarf/CMakeLists.txt
> were removed too, and it's not clear why.
> But it is definitely incorrect as written in the PR  and, at present,
> I don't have a usable CMakeLists.txt (in the local branch where the
> PR was applied)..

Most of this is included I think pic is changed in favor of the CMake solution POSITION_INDEPENT_CODE. Hidden stuffs are present too I think. Maybe the only missing part are the flags LIBDWARF_STATIC/BUILD

**Comment by flagarde** [comment]
Normally static and shared library should be handle by cmake depending on the option you pass. I will check again

**Comment by flagarde** [comment]
```cmake
# The -DPIC is so we find the right DW_API value in libdwarf.h with cmake with
# Linux. Dwarfgen requires all symbols in .so to be visible, so do not say
# hidden on libdwarf in that case.
if (BUILD_SHARED)
    if (NOT BUILD_DWARFGEN)
        set_target_properties(
            dwarf
            PROPERTIES C_VISIBILITY_PRESET hidden CXX_VISIBILITY_PRESET hidden
                       VISIBILITY_INLINES_HIDDEN YES
            )
    endif ()
    target_compile_definitions(dwarf PUBLIC LIBDWARF_BUILD)
    set_target_properties(dwarf PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
endif ()
```

**Comment by flagarde** [comment]
> A misunderstanding, if no dwarfgen, then there should be no libdwarfp either. Fixed that.
> 
> A bigger problem is that libdwarf.a is never installed, even if a static library is called for (and if a static called for, libdwarf.so should not be built or referenced). The pointless differences the IDE reformat created and the major changes made by hand make it unclear what is wrong. Puzzling over that now.

I see, there is some CMake don't follow the ${LIBDWARF_BUILD_TYPE}, I can use a condition in place of this variable this should solve the problem

**Comment by flagarde** [comment]
If I understand correctly for now you don't allow STATIC and SHARED compilation at the same time but only one of them?

**Comment by flagarde** [comment]
Could you tell me which critical part is missing?

**Comment by flagarde** [comment]
Now with : -G Ninja  -DWALL:BOOL=TRUE -DBUILD_DWARFGEN:BOOL=YES -DBUILD_DWARFEXAMPLE:BOOL=YES -DBUILD_SHARED=TRUE -DBUILD_NON_SHARED=FALSE -DDO_TESTING:BOOL=YES -DCMAKE_INSTALL_PREFIX=./toto

image

Now with : -G Ninja  -DWALL:BOOL=TRUE -DBUILD_DWARFGEN:BOOL=YES -DBUILD_DWARFEXAMPLE:BOOL=YES -DBUILD_SHARED=FALSE -DBUILD_NON_SHARED=TRUE -DDO_TESTING:BOOL=YES -DCMAKE_INSTALL_PREFIX=./toto

image

**Comment by flagarde** [comment]
On part I skipped is the lib32/lib64 selection. CMake should do that automatically if I remember well

**Comment by davea42** [comment]
All the problems with cmake libdwarf builds and shared/nonshared
are equally an issue with cmake libdwarfp.  The detailed code
to get them correct (as in v0.7.1) was removed.

**Comment by flagarde** [comment]
I have made some changes to compile both libraries shared or static in the PR? This is still not enough?

**Comment by davea42** [comment]
I did a git pull and took a look. There is nothing in either library build CMakeLists.txt
to provide the correct -D  defines for the builds to be correct. See the project
'main' for the original such file for the -D defines required.
The original base CMakeLists.txt and the library builds CM*txt 
did all that properly.  Why not use that and fix whatever in those conflicts
with your Fetch situation?

On testing:
I don't understand (from your initial snippet) how to use that cmake feature
and for it to work in future I need to somehow test, here. (which need not
be built into libdwarf-code.  Suggestions? A small complete example?

**Comment by flagarde** [comment]
Sure the formating + to much changes at the same time it's a mess (sorry for that). If you are still interested, I can try to split the steps and focus on library libdwarf first. This PR could be keep for reference for me. As the libdward is the core library as soon as this it's well checked and that you feel confident aboutthe change and cheks pass on your side other polishing could be done. What do you think about this strategy?

**Comment by davea42** [comment]
I have your PR data on file here and there is no reason to keep the PR open.
Thank you very much for all the effort you put into this.

I write a FetchContent testcase here, and...it does not fail!
maybe the testcase is just wrong?  I show it my testcase above.

Thanks again.

**Comment by davea42** [comment]
The mess was ... just a mess ...  That's not a real problem,
though the pointless reformatting was very annoying  :-).

The real problem (so far) is that so many things that the build took pains to
do (as they are essential) disappeared in the changes.  The easiest to mention
is that the crucial -D options for library builds vanished.  Oops. Those
are absolutely essential.  
Shared vs Non-shared libs, and when to have libdwarfp in the install
(and more) got changed. 

None of these changes (and likely more) were acceptable.  We designed
all the build mechanisms to behave (essentially) alike to serve lots of
different build requirements.  Over many years.

One key is the #ifdef at the start of  libdwarf.h as that makes
possible archive and properly-built shared-object/dll instances
(meaning things not in the API of libdwarf.h are hidden),
which was only fixed for Windows builds a few months ago (IIRC).

Admittedly it's not easy to grasp the requirements
of the build(s)  (generally not described in any
detail) from reading any of the build script texts!

I can readily believe that  some FetchContent use will fail
and in that case things have to be revisited.

But unless a revision is going to actually fix a problem I
do not think it's a good idea to revise the cmake.
Right now I do not know of a problem to fix.

So I would not advise attempting a revision of the cmake
at this time.  I have no concept of how a revision would
be an improvement (at present).  

I really appreciate your offer to work on this, but, well,
this does not seem to be the time to make a serious revision.
Thanks again for all the effort you put in to help.

**Comment by flagarde** [comment]
You are welcome, no problem.
I fully understand this PR is quite brutal and change too much things. The actual CMake script is able to compile but unfortunately is not enought : 

The reason is that why FetcContent the libdwarf project become part of the user project (a bit like add_subdirectory()), so any global variable in CMake affect the user project. Looking at the code, the most problematic one (for Fetchontent, not libdwarf itself) are the variables :

```cmake
# always include project's folder to includes
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_INCLUDE_CURRENT_DIR_IN_INTERFACE ON)

include_directories( ${PROJECT_BINARY_DIR} )
``` 
avoiding such variable need to use target_include_deirectories() but should not be very big changes.

On other change "cost-free" would be to add ALIAS to the libraries. 

```cmake
add_library(libdwarf::libdwarf ALIAS libdwarf)
```

the reason is that user could choose to use system-installed libdwarf, so as you provide a FindModule `libdwarf-config.cmake` etc... so the libdwarf::libdwarf would be available, but with FetchContent this libdwarf::libdwarf would not exist. Addind this ALIAS would solve this issue and would be free cost, fully compatible change

**Comment by davea42** [comment]
What I would really like to see is an  version of the cmake FetchContent
example in the libdwarf-regressiontests CmakeTest directory that
fails with current cmake due to the namespace issue.  Ideally the
new cmake file would be self contained and not very long .   
I think this is really crucial: Use current libdwarf-code cmake via FetchContent
and fail.

**Comment by davea42** [comment]
Pushed the fix to github. If I don't hear from you in a few days I will assume this is
truly fixed.

**Pull request closed without merging**
