### PR TITLE
Update zstd target handling and fix a small config error

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
This is an addition I found necessary while putting together a PR for conan https://github.com/conan-io/conan-center-index/pull/22629

### CODE REVIEW

**Comment by davea42** [comment]
Still marked as work in progress. ???   So not ready?

**Comment by jeremy-rifkin** [comment]
Hi Dave sorry for the confusion, I thought I had everything needed for package managers to be happy but it turns out not quite. I'll try to get that sorted out today/tomorrow and then I'll reply once this is ready

**Comment by jeremy-rifkin** [comment]
Alright, I think this should be good to go. The two package manager PR's are https://github.com/conan-io/conan-center-index/pull/22629 and https://github.com/microsoft/vcpkg/pull/36526.

**Comment by davea42** [comment]
Power out for 40 hours.   Then comcast would not come live. Now better.
Lots of catching up to do. will get to the as soon as I can.

**Comment by jeremy-rifkin** [comment]
Thanks dave, please let me know if there are any questions or if you spot anything that needs fixing

**Pull request merged**
