### PR TITLE
Include guards added, and IWYU performed en masse

### PR DESCRIPTION
**Pull request by judemille**
The reasoning is twofold:
- Code is much easier to reason about when headers do not rely on being included in specific positions, with other headers already included.
- Analysis tools, such as clangd (which powers many code editors), simply cannot effectively analyze headers that are written to be included in-context. Writing headers "out of context" allows them to be self-contained, and therefore, analyzed.

### CODE REVIEW

**Comment by judemille** [comment]
Realizing now that I also changed the default Meson options. Not in scope, I don't think, although, the default setting of `werror=true` makes the library fail to compile under MSVC. Setting the default build type like that also seems inadvisable to me, though I could change it back.

**Comment by vtorri** [comment]
normally werror=true should make the build fail as /WX should be passed

**Comment by vtorri** [comment]
i would have preferred smaller patches

**Comment by vtorri** [comment]
also please consider https://stackoverflow.com/questions/8649018/what-is-the-difference-between-ssize-t-and-ptrdiff-t

**Comment by judemille** [comment]
> normally werror=true should make the build fail as /WX should be passed

Yes, and I don't think that should be default.

**Comment by judemille** [comment]
> also please consider https://stackoverflow.com/questions/8649018/what-is-the-difference-between-ssize-t-and-ptrdiff-t

I'll put the `ssize_t` back.

**Comment by davea42** [comment]
It  requires analysis of every change as the reasoning varies so much. Very challenging.
Well, I'll wait till you are finished and look at #236 now.

**Comment by judemille** [comment]
I have another commit queued up, as part of my mission to make compilation with `/WX` succeed, to make at least most sizeof checks compile-time. Depends on this PR, but I don't think it's in scope for this.

**Comment by davea42** [comment]
I agree that removing project-header-includes-project-header is a good thing. Obviously we missed fixing some of those.
I won't be touching any of this since you are actively working on it.

**Comment by davea42** [comment]
Please note that a release is scheduled just after April 1.    So a large-scale change so late in 0.9.2
does not seem like a good idea.  Once it's released we'll call it 0.9.3 and go from there.

**Comment by judemille** [comment]
Seems reasonable to me. How does it sound to toss in a patch to 0.9.2 to turn off the default `werror=true`, so that it doesn't blow up in one's face by default?

**Comment by davea42** [comment]
I have not pulled or applied this patch anywhere.

So feel free to alter this patch as much as necessary.

But I think it too late and too big to add to 'main' until after the April2 release.

**Comment by judemille** [comment]
I might have been unclear. I meant to suggest a new patch, separate from (and not dependent on) this one, to remove the `werror=true` from the `meson.build` prior to 0.9.2.

**Comment by davea42** [comment]
Ok. I think I understand, and yes a small patch for the one werror issue you have will be fine
as anew  pull request, and I will check it and apply  'right now'.

**Comment by davea42** [comment]
With respect to the werror issue:  A simple diff of current 0.9.2 against the way you think is better
for that in 0.9.2 (posted here or email to libdwarf@linuxmail.org)  would suffice.
Your choice.

**Comment by davea42** [comment]
I've fixed the include situation in 0.9.3.
So I am closing this as completed.

I'd be happy to know if there are remaining issues I overlooked. So I can fix them.

**Pull request closed without merging**
