### PR TITLE
Rename Zstd target to be aligned with the upstream

### LINKED ISSUE #225: Update zstd cmake usage to the provided by the upstream
Hello! The project [Zstd](http://facebook.github.io/zstd/zstd_manual.html) does not have an official cmake config file, neither find cmake available in the official cmake modules.

However, the project itself offers cmake support, including a config file and targets:

https://github.com/facebook/zstd/blob/dev/build/cmake/zstdConfig.cmake

https://github.com/facebook/zstd/blob/dev/build/cmake/CMakeLists.txt#L181

So, consuming zstd would be:

```
find_package(zstd CONFIG REQUIRED)

...

target_link_libraries(dwarf PRIVATE $<TARGET_EXISTS:zstd::libzstd_static>,zstd::libzstd_static,zstd::libzstd_shared>)
```

This would follow the correct way, following the current zstd project. In order to have effect, it would need to update libdwarf-code CMakeLists.txt, and FindZTD.cmake in this project, to follow the expect names. 

In case you are inclined to accept the idea, I could open a PR with the fix.

### PR DESCRIPTION
**Pull request by uilianries**
Hello again, this is the implementation of the idea discussed in the issue #225

When building and installing zstd we will have the follow artifacts:

```
zstd/1.5.5: RUN: cmake --install "/Users/uilian/Development/zstd-1.5.5/build/Release" --prefix "/Users/uilian/zstd-1.5.5"
-- Install configuration: "Release"
-- Installing: /Users/uilian/zstd-1.5.5/lib/cmake/zstd/zstdTargets.cmake
-- Installing: /Users/uilian/zstd-1.5.5/lib/cmake/zstd/zstdTargets-release.cmake
-- Installing: /Users/uilian/zstd-1.5.5/lib/cmake/zstd/zstdConfig.cmake
-- Installing: /Users/uilian/zstd-1.5.5/lib/cmake/zstd/zstdConfigVersion.cmake
-- Installing: /Users/uilian/zstd-1.5.5/lib/pkgconfig/libzstd.pc
-- Installing: /Users/uilian/zstd-1.5.5/include/zstd.h
-- Installing: /Users/uilian/zstd-1.5.5/include/zdict.h
-- Installing: /Users/uilian/zstd-1.5.5/include/zstd_errors.h
-- Installing: /Users/uilian/zstd-1.5.5/lib/libzstd.a
-- Installing: /Users/uilian/zstd-1.5.5/bin/zstd
-- Installing: /Users/uilian/zstd-1.5.5/bin/zstdcat
-- Installing: /Users/uilian/zstd-1.5.5/bin/unzstd
-- Installing: /Users/uilian/zstd-1.5.5/bin/zstdgrep
-- Installing: /Users/uilian/zstd-1.5.5/bin/zstdless
-- Installing: /Users/uilian/zstd-1.5.5/share/man/man1/zstd.1
-- Installing: /Users/uilian/zstd-1.5.5/share/man/man1/zstdcat.1
-- Installing: /Users/uilian/zstd-1.5.5/share/man/man1/unzstd.1
-- Installing: /Users/uilian/zstd-1.5.5/share/man/man1/zstdgrep.1
-- Installing: /Users/uilian/zstd-1.5.5/share/man/man1/zstdless.1
-- Installing: /Users/uilian/zstd-1.5.5/bin/zstdmt
```

As extra reference, you can check AUR (BTW I use Arch): https://archlinux.org/packages/core/x86_64/zstd/files/

```
...
usr/lib/cmake/zstd/
usr/lib/cmake/zstd/zstdConfig.cmake
usr/lib/cmake/zstd/zstdConfigVersion.cmake
usr/lib/cmake/zstd/zstdTargets-none.cmake
usr/lib/cmake/zstd/zstdTargets.cmake
```

So, this PR renames the `FindZSTD.cmake` to `Findzstd.cmake`. As result, we need to rename `ZSTD_FOUND` to follow CMake behavior. Then, we can use `find_package(zstd)` with safety.

Other custom variables like `ZSTD_LIB`, are not required to be changed, but the upstream only generates CMake targets like `zstd::static_library`, but no variables. All CMake targets used in this project are following Zstd as equally named by the upstream, so no changes are required too.

Locally, running on Mac M1 + CMake 3.25 + Apple Clang 15 + Zstd 1.5.5 (brew), it works:

```
% cmake -S . -B build  -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_NON_SHARED=ON -DBUILD_SHARED=OFF
-- The C compiler identification is AppleClang 15.0.0.15000100
-- The CXX compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building dwarfgen    ... OFF
-- Building dwarfexample... OFF
-- Building api tests   ... 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for stdafx.h
-- Looking for stdafx.h - not found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Performing Test HAVE_UINTPTR_T
-- Performing Test HAVE_UINTPTR_T - Success
-- Performing Test HAVE_INTPTR_T
-- Performing Test HAVE_INTPTR_T - Success
-- HAVE_UINTPTR_T 1: uintptr_t defined in stdint.h... YES
-- uintptr_t value considered NO 
-- HAVE_INTPTR_T 1: intptr_t defined in stdint.h... YES
-- intptr_t value considered NO 
-- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/libz.tbd (found version "1.2.12") 
-- Found zstd: /opt/homebrew/lib/libzstd.dylib (found version "1.5.5") 
-- CMAKE_SIZEOF_VOID_P ... 8
-- Compiler warning options... NO
-- Install prefix ... /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/uilian/Development/libdwarf-code/build
```

closes #225

### CODE REVIEW

**Comment by davea42** [comment]
I'll test this on MacOS and FreeBSD 32bit (via removing zstd there for the test) today.

**Comment by uilianries** [comment]
Thank you!

**Comment by davea42** [comment]
linux and freebsd cmake build/install  with libzstd present I get:

- Installing: /tmp/cmaketarg/lib/cmake/libdwarf/libdwarf-targets-noconfig.cmake
-- Installing: /tmp/cmaketarg/lib/pkgconfig/libdwarf.pc
CMake Error at src/lib/libdwarf/cmake_install.cmake:97 (file):
  file INSTALL cannot find "/home/davea/dwarf/code/cmake/FindZSTD.cmake": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
===========
This build uses cmake with ninja.

**Comment by davea42** [comment]
Ah. That FindZSTD appears in libdwarf/CMakeLists.txt

**Comment by davea42** [comment]
Yes, altering  libdwarf/CMakeLists.txt fixes the install.
Could you please update your pull request? Thanks.

**Comment by davea42** [comment]
If, on Macos, i port uninstall name:zstd that breaks cmake.
On freebsd removing zstd breaks gcc.

Basically I don't really know how to test that the changes work in a case where
zstd is not required.

**Comment by davea42** [comment]
I'll do the fix here. Taking pull req. as is.

**Comment by davea42** [comment]
Fixed the identified issue and pushed to sourceforge.

**Comment by flagarde** [comment]
@uilianries Hi, ideed it is better in lowercase but it seems you PR didnnt change the names in libdwarfConfig.cmake.in

**Comment by uilianries** [comment]
> @uilianries Hi, indeed it is better in lowercase but it seems you PR didnnt change the names in libdwarfConfig.cmake.in

@flagarde Sorry, I really forgot to check that file. I just opened a new PR fixing it: https://github.com/davea42/libdwarf-code/pull/227

**Pull request merged**
