### PR TITLE
Cmake changes for zlib and zstd

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
The main change here is adding `find_dependency(ZLIB)` and `find_dependency(ZSTD)` to libdwarf's config file. There may be other tweaks needed down the road, for example after building and installing zstd from source on windows/minwg libdwarf doesn't seem to be finding it, however this PR should be a step towards the right direction.

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
cc @flagarde

**Comment by flagarde** [comment]
I guess the problem with not finding the ZSTD is because of the strange CMakeLists.txt of ZSTD repo. I need to have a better look on their file

**Comment by vtorri** [comment]
it works without tweaks like that with meson...

**Comment by flagarde** [comment]
It's not really a trick. It is just an helper to let CMake see if all dependencies are found.

It worked before this mostly in many cases because zlib and zstd are quite common and most of the time already installed and in the good path. However it can happen they are not installed or in the wrong path.

Adding these lines ask CMake to check for them  and if they are not found to crash with a nice message saying mostly : Sorry I can't find libdward because one of its dependencies is not found.

We a have case here concretely I think with what I guess @jeremy-rifkin tries to do:

ZSTD is not present on system so he uses FetchContent. Libdwarf can then find it and compile. both are installed but it seems ZSTD cmake file do something strange and install ZSTD in strange folder or things like that..

@jeremy-rifkin would guess all is good and try to use libdwarf in other project doing :

Find_package(libdwarf)

with this PR we can know a config time something is wrong with ZSTD and stop the config on CMake. Otherwise the problem would be at linking time in this case (libzstd.so not present)

**Comment by flagarde** [comment]
For now the CMake file just ask cmake to link libdwarkd with zstd and zlib but no check to see if this will be possible is done. This PR do that checks

**Pull request merged**
