### PR TITLE
Use pkg-config to detect zlib

### PR DESCRIPTION
**Pull request by vtorri**

### CODE REVIEW

**Comment by davea42** [comment]
make[1]: Entering directory '/var/tmp/bld/src/bin/dwarfdump'
  CCLD     dwarfdump
gcc: error: DWARF_LIBS@: No such file or directory
make[1]: *** [Makefile:673: dwarfdump] Error 1
make[1]: Leaving directory '/var/tmp/bld/src/bin/dwarfdump'

**Comment by davea42** [comment]
There is no AC_SUBST, AC_ARGVAR for DWARF_LIBS?

**Comment by davea42** [comment]
This fixed it.
+AC_SUBST([DWARF_LIBS])
+AC_ARG_VAR([DWARF_LIBS], [extra linker flags when linking dwarfdump])

**Comment by vtorri** [comment]
normally PKG_CHECK_MODULES takes care of that, i've never added that

**Pull request merged**
