### PR TITLE
Allow choosing an MSVC runtime

### PR DESCRIPTION
**Pull request by jgcodes2020**
This also bumps CMake to version 3.15. Might be able to keep the 3.2 versions using some version checks and whatnot.

### CODE REVIEW

**Comment by davea42** [comment]
Why do you want to change minimum cmake version to 3.15 (from 3.2)?

**Comment by jgcodes2020** [comment]
> Why do you want to change minimum cmake version to 3.15 (from 3.2)?

3.15 adds `CMAKE_MSVC_RUNTIME_LIBRARY`, which makes it very convenient to set the runtime library. As I said, I could extend this to cmake 3.2 by setting `CMAKE_CXX_FLAGS`, but I am unsure if this will affect any existing buildscript code.

**Comment by jgcodes2020** [comment]
Note: I actually need a minimum of 3.3 to accomodate multi-configuration build systems like Visual Studio.

**Comment by davea42** [comment]
Some Linux environments in current use (Ubuntu 18.04)
have cmake 3.10.2.   The current Ubuntu Long term Support
(20.04) has cmake 3.16.3.  
FreeBSD 12 has cmake 3.19.2.

That 18.04 situation means I  do not want to force all cmake users to
have 3.15.  At least for now.

For the Windows MSVC case you could add to CXX_FLAGS 
and that would be fine.
So the pull request needs to be redone so I can
accept it. 

Closing this, and I look forward to a new pull request.

**Pull request closed without merging**
